In [31]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

data = {
    "study_hours": [1, 2, 3, 3, 4, 4, 5, 6, 7, 8],
    "attendance": [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)

# 입력값과 정답 분리
X = df[["study_hours", "attendance"]]
y = df["pass_fail"]

model = DecisionTreeClassifier(random_state=42)
model.fit(X,y)

print("데이터 준비 완료")
print(f"학생 수: {len(df)}명") # 학생 수: %%명

데이터 준비 완료
학생 수: 10명

# 모델 정확도 

- 학습에 사용한 데이터로 정확도 확인

In [2]:
accuracy = model.score(X,y)
print("모델 정확도:", accuracy) # 0~1 표시됨 -> 0~100%
print(f"모델 정확도 퍼센트:{accuracy * 100}%")

모델 정확도: 1.0
모델 정확도 퍼센트:100.0%

In [14]:
# 모델이 어떤 예측을 했는지 확인
predictions = model.predict(X)

# Columns - 공부시간,출석률,실제,예측,결과
# zip() =>zip([1,2,3]), ([4,5,6]) => (1,4),(2,5),(3,6)
# 실제값과 예측값을 한쌍으로 묶어서..
result = pd.DataFrame({
    "공부시간" : X["study_hours"].values,
    "출석률" : X["attendance"].values,
    "실제값": y.values,
    "예측": predictions,
    "결과": ["0" if a == p else "x" for a, p in zip(y, predictions)] # zip (실제값,예측값),배열 처리
    
})
result

   공부시간  출석률  실제값  예측 결과
0     1   50    0   0  0
1     2   55    0   0  0
2     3   60    0   0  0
3     3   80    1   1  0
4     4   60    0   0  0
5     4   75    1   1  0
6     5   75    1   1  0
7     6   80    1   1  0
8     7   90    1   1  0
9     8   95    1   1  0

# 딕셔너리 

key-value 한쌍으로 이루어진 집합(자료형)

- List -> 번호표가 있는 사물함(0번,1번,2번,...)
- Dictionary -> 이름표가 있는 사물함 (학번, 이름, 학년)

In [21]:
# 리스트
student_list = ["kim", 20, 50]
print(f"리스트에서 이름 출력: {student_list[0]}")

# 딕셔너리
student_dict = {"name": "kim", "age": 20, "score" :50}

student_dict = {"name": "kim", "age": 20}

리스트에서 이름 출력: kim

리스트에서 이름 출력: kim
딕셔너리에서 이름 출력: kim

In [27]:
person = {
    "name":"이재호",
    "age" : 20,
    "major": "AI응용프로그래밍" 
}

# 전체 출력
print(person)

# 나이
print(person["age"])

# 과목
print(person["major"])

{'name': '이재호', 'age': 20, 'major': 'AI응용프로그래밍'}
20
AI응용프로그래밍

In [28]:
person["age"] = 21
print(person["age"], person)

# 성별 추가
person["gender"] ="male"
print (person)

#성별 삭제
del person["gender"]
print(person)

21 {'name': '이재호', 'age': 21, 'major': 'AI응용프로그래밍'}
{'name': '이재호', 'age': 21, 'major': 'AI응용프로그래밍', 'gender': 'male'}
{'name': '이재호', 'age': 21, 'major': 'AI응용프로그래밍'}

1 # 문제

- 사과, 바나나, 포도는 각 1000원, 2000원, 3000원 이다.
    - 딕셔너리 로그 출력
- 사과의 가격을 10% 할인하고 바나나는 13% 인상했을때,    
    - Python 코드로 작성
- 사과 , 바나나, 포도의 가격표를 표시하시오.
    - (DataFrame사용)

In [49]:
import pandas as pd


fruit_prices = {
    '사과': 1000,
    '바나나': 2000,
    '포도': 3000
}

print("--- 초기 가격 딕셔너리 ---")
print(fruit_prices)
print("\n")

fruit_prices['사과'] = int(fruit_prices['사과'] * 0.9)

fruit_prices['바나나'] = int(fruit_prices['바나나'] * 1.13)

# 딕셔너리를 리스트 형태로 변환하여 DataFrame 생성
df_prices = pd.DataFrame(list(fruit_prices.items()), columns=['과일', '가격(원)'])

# 인덱스를 1부터 시작하도록 깔끔하게 정리 (선택 사항)
df_prices.index = df_prices.index + 1

print("--- 변동 후 과일 가격표 ---")
print(df_prices)

--- 초기 가격 딕셔너리 ---
{'사과': 1000, '바나나': 2000, '포도': 3000}


--- 변동 후 과일 가격표 ---
    과일  가격(원)
1   사과    900
2  바나나   2260
3   포도   3000

## 딕셔너리와 반복문 함께 사용

In [29]:
scores = {
    "국어" : 88,
    "수학" : 76,
    "영어" : 92
}

# 로그 출력 ------
# 국어: 88점
# 수학: 76점
# 영어: 92점

for subject, score in scores.items():
    print(f"{subject}: {score}점")

국어: 88점
수학: 76점
영어: 92점

In [9]:
# 80점 이상인 과목만 출력
for subject, score in scores.items():
    if score >= 80:
        print(f"80점 이상인 과목: {subject}")

80점 이상인 과목: 국어
80점 이상인 과목: 영어

# Pandas DataFrame 다루기

In [32]:
data = {
    "study_hours": [1, 2, 3, 3, 4, 4, 5, 6, 7, 8],
    "attendance": [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)
df

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0
3            3          80          1
4            4          60          0
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

In [34]:
#상위 3줄만 보기 head (숫자)

print(df.head(3))

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0

In [35]:
# 상위 3줄만 연결
# count - 데이터 개수
# mean - 평균값 (전체/개수)
# std - 표준편차 (평균에서 얼마나 퍼져있는지, 클수록 편차가 큼)
# min - 최소값 (최솟값)
# 25% - 하위 25%
# 50% - 중앙값
# 75% - 상위 75%
# max - 최대값 (최댓값)
df.describe()

       study_hours  attendance  pass_fail
count    10.000000   10.000000  10.000000
mean      4.300000   72.000000   0.600000
std       2.213594   15.129074   0.516398
min       1.000000   50.000000   0.000000
25%       3.000000   60.000000   0.000000
50%       4.000000   75.000000   1.000000
75%       5.750000   80.000000   1.000000
max       8.000000   95.000000   1.000000

In [33]:
1 # 조건으로 데이터 골라내기
high_attendance = df[df["attendance"] >= 70]
# high_attendance

# 합격한 학생만 출력
pass_student = df[df["pass_fail"] == 1]
pass_student

   study_hours  attendance  pass_fail
3            3          80          1
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

# 날씨 예측

In [50]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [51]:
#데이터 준비 

weather_data = {
    "clouds" : [10, 20, 30 , 40, 50 , 60, 70, 80, 90, 95, 40],
    "humidity": [30, 35, 40, 55, 65, 70, 80, 85, 90, 45],
    "umbrella": [0, 0, 0, 0, 1, 1, 1, 1, 1, 0]
}

weather_df = pd.DataFrame(weather_data)
weather_df

ValueError: All arrays must be of the same length

In [ ]:
# 입력값과 정답 분리

X_weather = weather_df[["clouds","humidity"]]
y_weather = weather_df["umbrella"]

print("입력값과 정답 분리 완료!")

NameError: name 'weather_df' is not defined

In [ ]:
# 모델 만들기 + 학습
weather_model = DecisionTreeClassifier(random_state=42)
weather_model.fit(X_weather, y_weather)
print("모델 학습 완료")

NameError: name 'X_weather' is not defined

In [ ]:
# 예측하기

test_weather = pd.DataFrame([
    [20, 35], # 구름 적음, 습도 낮음
    [55, 60], # 구름 보통, 습도 보통
    [85, 88], # 구름 많음, 습도 높음
],columns=["clouds", "humidity"])

predictions = weather_model.predict(test_weather)

# 로그 출력 -----------
# 구름 ?%, 습도 ?% -> 우산 필요|불필요

NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

## 문제 
# 아래 로그 개별 출력
# 구름 ?%, 습도 ?% -> 우산 필요|불필요
- 예시)구름 20% 습도 35% -> 우산 불필요

In [47]:

test_weather['predict'] = predictions

for i, row in test_weather.iterrows():
    need_umbrella = "필요" if row['predict'] == 1 else "불필요"
    print(f"구름 {row['clouds']}%, 습도 {row['humidity']}% -> 우산 {need_umbrella}")

NameError: name 'predictions' is not defined

In [ ]:
# 모델 정확도 구하기

weather_model.score(X_weather,y_weather)
print(f"모델 정확도: {acc * 100}%")

In [ ]:
# 모델 정확도 낮추기
# 애매한 데이터를 포함한 날씨 데이터

messy_data = {
    "cloudy": [10, 20, 55, 55, 60, 70, 80, 90],
    "humidity": [30, 35, 60, 60, 65, 70, 80, 85],
    "umbrella": [0, 0, 0, 1, 1, 1, 1, 1,]
}

messy_df =pd.DataFrame(messy_data)

X_messy = messy_df[["clouds", "humidity"]]
y_messy = messy_df[["umbrella"]]

messy_model = DecisionTreeClassifier(random_state=42)
messy_model.fit(X_messy,y_messy)

messy_acc = messy_model.score(X_messy, y_messy)
print(f"애매한 데이터 모델 정확도: {messy_acc * 100}%")

print()

messy_pred = messy_model.predict(X_messy)
result = pd.DataFrame([
    "구름": X_messy["clouds"].values,
    "습도": X_messy["humidity"].values,
    "실제": y_messy.values
    "예측": messy_pred
    "결과":
])

KeyError: "['clouds'] not in index"